@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml

Person(analyst, "Stock Analyst", "Uses the console application to retrieve and analyze stock data")
System(swat_stock, "SwatStockConsole", "Console application for retrieving and displaying stock data")
System_Ext(alpha_vantage, "Alpha Vantage API", "Third-party financial market data API")

Rel(analyst, swat_stock, "Uses", "CLI")
Rel(swat_stock, alpha_vantage, "Retrieves stock data", "API requests")

@enduml