@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

System_Boundary(swat, "SwatStockConsole") {
    Container(console, "Console Application", "C#", "Handles user interaction and coordination")
    Container(api, "API Service", "C#", "Retrieves stock data from Alpha Vantage API")
    Container(chart, "Chart Service", "C#", "Generates visual stock charts")
    Container(models, "Data Models", "C#", "Defines data structures (DailyPriceData, APIData)")
    Container(utils, "Utilities", "C#", "Provides JSON parsing (JsonUtility)")
}

System_Ext(alpha, "Alpha Vantage API", "External stock data provider")

Rel(console, api, "Uses to fetch data", "HTTP")
Rel(api, alpha, "Makes API calls to", "REST API")
Rel(api, utils, "Uses for JSON processing", "JSON Utility")
Rel(console, chart, "Requests charts from", "")
Rel(chart, models, "Uses data models", "")
Rel(api, models, "Stores data in", "")
@enduml