@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

Container_Boundary(swatstock, "SwatStockConsole") {
    Component(Program, "Program", "C#", "Entry point")
    Component(Client, "Client", "C#", "Retrieves stock data")
    Component(AlphaVantageApiService, "AlphaVantageApiService", "C#", "Fetches API data")
    Component(ChartService, "ChartService", "C#", "Generates charts")
    Component(JsonUtility, "JsonUtility", "C#", "Handles JSON processing")
    
    Interface(IAlphaVantageApiService, "IAlphaVantageApiService")
    Interface(IChartService, "IChartService")

    Rel_D(Program, Client, "Uses")
    Rel_D(Client, IAlphaVantageApiService, "Uses")
    Rel_U(AlphaVantageApiService, IAlphaVantageApiService, "Implements")
    Rel_D(AlphaVantageApiService, JsonUtility, "Uses")
    Rel_D(Program, ChartService, "Uses")
    Rel_U(ChartService, IChartService, "Implements")
}
@enduml