@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml

Person(stock_analyst, "Stock Analyst", "Uses the console application to access stock data")

System(swat_stock_console, "SwatStockConsole", "A console application for retrieving and displaying stock data")

System_Ext(alpha_vantage, "Alpha Vantage API", "External API for real-time and historical stock data")

Rel(stock_analyst, swat_stock_console, "Uses")
Rel(swat_stock_console, alpha_vantage, "Retrieves stock data using", "HTTP")

@enduml